// source snippet: key=macro_recursive  prefix=macro_recursive

mod capture {
    #[doc = " Macro that returns a recursive function that (semi-)automatically captures."]
    #[doc = ""]
    #[doc = " # Example"]
    #[doc = " default version"]
    #[doc = " ```"]
    #[doc = " # use competitive::crecurse;"]
    #[doc = " let mut res = 0usize;"]
    #[doc = " let coeff = 3usize;"]
    #[doc = " crecurse!("]
    #[doc = "     // (1) semi-automatically capture mutable reference (res: &mut usize)"]
    #[doc = "     [res: usize],"]
    #[doc = "     fn mul(x: usize, y: usize) {"]
    #[doc = "         if y > 0 {"]
    #[doc = "             if y % 2 == 1 {"]
    #[doc = "                 // (2) automatically capture reference (coeff: &usize)"]
    #[doc = "                 *res += coeff * x;"]
    #[doc = "             }"]
    #[doc = "             // (3) call macro to recurse"]
    #[doc = "             mul!(x + x, y / 2);"]
    #[doc = "         }"]
    #[doc = "     }"]
    #[doc = " )(10, 19); // (4) macro returns captured version of the recursive function"]
    #[doc = " assert_eq!(res, coeff * 10 * 19);"]
    #[doc = " ```"]
    #[doc = ""]
    #[doc = " unsafe version (automatically capture everything)"]
    #[doc = " ```"]
    #[doc = " # use competitive::crecurse;"]
    #[doc = " let mut res = 0usize;"]
    #[doc = " let coeff = 3usize;"]
    #[doc = " crecurse!("]
    #[doc = "     unsafe fn mul(x: usize, y: usize) {"]
    #[doc = "         if y > 0 {"]
    #[doc = "             if y % 2 == 1 {"]
    #[doc = "                 res += coeff * x;"]
    #[doc = "             }"]
    #[doc = "             mul!(x + x, y / 2);"]
    #[doc = "         }"]
    #[doc = "     }"]
    #[doc = " )(10, 19);"]
    #[doc = " assert_eq!(res, coeff * 10 * 19);"]
    #[doc = " ```"]
    #[doc = ""]
    #[doc = " no overhead version (semi-automatically capture everything)"]
    #[doc = " ```"]
    #[doc = " # use competitive::crecurse;"]
    #[doc = " let mut res = 0usize;"]
    #[doc = " let coeff = 3usize;"]
    #[doc = " crecurse!("]
    #[doc = "     [res: &mut usize, coeff: &usize],"]
    #[doc = "     static fn mul(x: usize, y: usize) {"]
    #[doc = "         if y > 0 {"]
    #[doc = "             if y % 2 == 1 {"]
    #[doc = "                 *res += coeff * x;"]
    #[doc = "             }"]
    #[doc = "             mul!(x + x, y / 2);"]
    #[doc = "         }"]
    #[doc = "     }"]
    #[doc = " )(10, 19);"]
    #[doc = " assert_eq!(res, coeff * 10 * 19);"]
    #[doc = " ```"]
    #[doc = ""]
    #[doc = " # Syntax"]
    #[doc = " ```txt"]
    #[doc = " crecurse!("]
    #[doc = "     ([($ident: $type),*,?],)?"]
    #[doc = "     (unsafe|static)? fn $ident\\(($ident: $type),*,?\\) (-> $type)? $block"]
    #[doc = " )"]
    #[doc = " ```"]
    #[macro_export]
    macro_rules!crecurse{(@macro_def($dol:tt)$name:ident$($cargs:ident)*)=>{#[allow(unused_macros)]macro_rules!$name{($dol($dol args:expr),*)=>{$name($dol($dol args,)*$($cargs,)*)}}};(@static[$(($cargs:ident,$cargsexpr:expr,$cargsty:ty))*][$(,)?],fn$func:ident($($args:ident:$argsty:ty),*$(,)?)->$ret:ty$body:block)=>{{fn$func($($args:$argsty,)*$($cargs:$cargsty,)*)->$ret{$crate::crecurse!(@macro_def($)$func$($cargs)*);$body}|$($args:$argsty,)*|->$ret{$func($($args,)*$($cargsexpr,)*)}}};(@static[$($pcaps:tt)*][$(,)?],fn$func:ident($($argstt:tt)*)$($rest:tt)*)=>{$crate::crecurse!(@static[$($pcaps)*][],fn$func($($argstt)*)->()$($rest)*)};(@static[$($pcaps:tt)*][$carg:ident:&mut$cargty:ty,$($caps:tt)*],$($rest:tt)*)=>{$crate::crecurse!(@static[$($pcaps)*($carg,&mut$carg,&mut$cargty)][$($caps)*],$($rest)*)};(@static[$($pcaps:tt)*][$carg:ident:&$cargty:ty,$($caps:tt)*],$($rest:tt)*)=>{$crate::crecurse!(@static[$($pcaps)*($carg,&$carg,&$cargty)][$($caps)*],$($rest)*)};(@static[$($pcaps:tt)*][$carg:ident:$cargty:ty,$($caps:tt)*],$($rest:tt)*)=>{$crate::crecurse!(@static[$($pcaps)*($carg,$carg,$cargty)][$($caps)*],$($rest)*)};($([$($caps:tt)*],)?static fn$func:ident($($args:ident:$argsty:ty),*$(,)?)$($rest:tt)*)=>{$crate::crecurse!(@static[][$($($caps)*)?,],fn$func($($args:$argsty),*)$($rest)*)};(@default[$($cargs:ident:$cargsty:ty),*$(,)?],fn$func:ident($($args:ident:$argsty:ty),*$(,)?)->$ret:ty$body:block)=>{{fn call<F>(f:&F,$($args:$argsty,)*$($cargs:&mut$cargsty,)*)->$ret where F:Fn(&dyn Fn($($argsty,)*$(&mut$cargsty,)*)->$ret,$($argsty,)*$(&mut$cargsty,)*)->$ret,{f(&|$($args:$argsty,)*$($cargs:&mut$cargsty,)*|->$ret{call(f,$($args,)*$($cargs,)*)},$($args,)*$($cargs,)*)}|$($args:$argsty,)*|->$ret{call(&|$func,$($args:$argsty,)*$($cargs:&mut$cargsty,)*|->$ret{$crate::crecurse!(@macro_def($)$func$($cargs)*);$body},$($args,)*$(&mut$cargs,)*)}}};(@default[$($caps:tt)*],fn$func:ident($($argstt:tt)*)$($rest:tt)*)=>{$crate::crecurse!(@default[$($caps)*],fn$func($($argstt)*)->()$($rest)*)};($([$($caps:tt)*],)?fn$func:ident($($args:ident:$argsty:ty),*$(,)?)$($rest:tt)*)=>{$crate::crecurse!(@default[$($($caps)*)?],fn$func($($args:$argsty),*)$($rest)*)};(@unsafe[$($cargs:ident:$cargsty:ty),*$(,)?],fn$func:ident($($args:ident:$argsty:ty),*$(,)?)->$ret:ty$body:block)=>{{fn call<F>(f:&mut F,$($args:$argsty,)*$($cargs:&mut$cargsty,)*)->$ret where F:FnMut(&mut dyn FnMut($($argsty,)*$(&mut$cargsty,)*)->$ret,$($argsty,)*$(&mut$cargsty,)*)->$ret,{let fp=f as*mut F;(unsafe{&mut*fp})(&mut|$($args:$argsty,)*$($cargs:&mut$cargsty,)*|->$ret{call(unsafe{&mut*fp},$($args,)*$($cargs,)*)},$($args,)*$($cargs,)*)}|$($args:$argsty,)*|->$ret{call(&mut|$func,$($args:$argsty,)*$($cargs:&mut$cargsty,)*|->$ret{$crate::crecurse!(@macro_def($)$func$($cargs)*);$body},$($args,)*$(&mut$cargs,)*)}}};(@unsafe[$($caps:tt)*],fn$func:ident($($argstt:tt)*)$($rest:tt)*)=>{$crate::crecurse!(@unsafe[$($caps)*],fn$func($($argstt)*)->()$($rest)*)};($([$($caps:tt)*],)?unsafe fn$func:ident($($args:ident:$argsty:ty),*$(,)?)$($rest:tt)*)=>{$crate::crecurse!(@unsafe[$($($caps)*)?],fn$func($($args:$argsty),*)$($rest)*)};($($t:tt)*)=>{::std::compile_error!(::std::concat!("invalid input: ",::std::stringify!($($t)*)))};}
    #[doc = " Automatic memorization for recursive functions."]
    #[doc = ""]
    #[doc = " This macro binds memorized version of the recursive functions to a local variable."]
    #[doc = " The specification of the function declaration part is the same as [`crecurse`]."]
    #[doc = ""]
    #[doc = " [`crecurse`]: crate::crecurse"]
    #[doc = ""]
    #[doc = " # Example"]
    #[doc = " ```"]
    #[doc = " # use competitive::memorize;"]
    #[doc = " memorize!("]
    #[doc = "     fn comb(n: usize, r: usize) -> usize {"]
    #[doc = "         if r > n {"]
    #[doc = "             0"]
    #[doc = "         } else if r == 0 || r == n {"]
    #[doc = "             1"]
    #[doc = "         } else {"]
    #[doc = "             comb!(n - 1, r) + comb!(n - 1, r - 1)"]
    #[doc = "         }"]
    #[doc = "     }"]
    #[doc = " );"]
    #[doc = " assert_eq!(comb(30, 12), 86493225);"]
    #[doc = " ```"]
    #[macro_export]
    macro_rules!memorize{(@inner[$map:ident,$Map:ty,$init:expr]fn$name:ident($($args:ident:$argsty:ty),*$(,)?)->$ret:ty$body:block)=>{let mut$map:$Map=$init;#[allow(unused_mut)]let mut$name=$crate::crecurse!([$map:$Map],fn$name($($args:$argsty),*)->$ret{if let Some(value)=$map.get(&($($args,)*)).cloned(){value}else{let value=(||$body)();$map.insert(($($args,)*),value.clone());value}});};(fn$name:ident($($args:ident:$argsty:ty),*$(,)?)->$ret:ty$body:block)=>{$crate::memorize!(@inner[__memorize_map,::std::collections::HashMap<($($argsty,)*),$ret>,::std::default::Default::default()]fn$name($($args:$argsty),*)->$ret$body);}}
}
